---
#######################################
# AUTHENTICATION OPTION 2:            #
#                          Using OIDC #
#######################################
name: Deploy transformations using OIDC auth-flow

on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy transformations
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Extract branch name
              shell: bash
              # If branch name has hyphens, replace with underscores
              run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/} | sed -e s/-/_/g)"
              id: extract_name

            - name: Resolve secrets
              shell: bash
              env:
                  BRANCH: ${{ steps.extract_name.outputs.name }}
              run: |
                  echo "##[set-output name=jetfire_client_secret;]$(echo jetfire_client_secret_${BRANCH})"
                  echo "##[set-output name=cognite_client_secret;]$(echo cognite_client_secret_${BRANCH})"
              id: extract_secrets

            - name: Deploy transformations
              uses: cognitedata/jetfire-cli@v2
              env:
                  # Credentials to be used when running your transformations,
                  # as referenced in your manifests:
                  COGNITE_CLIENT_ID: 0e457315-6830-4b80-8334-e6e5fd5c7b4e
                  COGNITE_CLIENT_SECRET: ${{ secrets[steps.extract_secrets.outputs.cognite_client_secret] }}
              with:
                  path: transformations_oidc
                  client-id: 0e457315-6830-4b80-8334-e6e5fd5c7b4e
                  client-secret: ${{ secrets[steps.extract_secrets.outputs.jetfire_client_secret] }}
                  project-name: extractor-bluefield-testing
                  token-url: https://login.microsoftonline.com/b86328db-09aa-4f0e-9a03-0136f604d20a/oauth2/v2.0/token
                  scopes: https://bluefield.cognitedata.com/.default
                  cluster: bluefield